name: Regression Tests on Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  regression-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run regression tests
        run: npm run cy:run:regression

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: regression-test-results
          path: cypress/results 
